components:
  schemas:
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
info:
  description: This is a test api sandbox utilizing api flask to generate documentation
  title: APIFlask
  version: 0.1.0
openapi: 3.0.3
paths:
  /:
    get:
      description: this is the index
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful response
      summary: index
  /200:
    get:
      description: this is the hello world route
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: OK
      summary: hello world
  /404:
    get:
      description: this is the 404 page
      parameters: []
      responses:
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not Found
      summary: 404 page
tags: []

